spring.application.name=notification-service

# server.port=8084
server.port=${SERVER_PORT:8084}

# KAFKA
# spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

spring.kafka.consumer.group-id=notificationService

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.techie.microservices.notification.event.OrderPlacedEvent

# KAFKA CONSUMER
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages=com.techie.microservices.order.event

# MAIL
# spring.mail.host=${SPRING_MAIL_HOST:sandbox.smtp.mailtrap.io}
# spring.mail.port=${SPRING_MAIL_PORT:2525}
# spring.mail.username=${SPRING_MAIL_USERNAME:username}
# spring.mail.password=${SPRING_MAIL_PASSWORD:password}

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# ACTUATOR
management.endpoints.web.exposure.include=health,info,metrics

# LOGGING
logging.level.root=INFO
logging.level.com.techie.microservices.notification=DEBUG



