trigger: none

pool:
  name: e-commerce-pool
  demands:
    - Agent.Name -equals azuredevops-deployer

steps:
  - task: AWSCLI@1
    displayName: "Verify AWS OIDC identity"
    inputs:
      awsCredentials: "AWS-ECR-OIDC"
      regionName: "ap-south-1"
      awsCommand: "sts"
      awsSubCommand: "get-caller-identity"

  - task: AWSCLI@1
    displayName: "Verify ECR access"
    inputs:
      awsCredentials: "AWS-ECR-OIDC"
      regionName: "ap-south-1"
      awsCommand: "ecr"
      awsSubCommand: "describe-repositories"
      awsArguments: "--repository-names ecommerce/api-gateway ecommerce/product-service ecommerce/inventory-service ecommerce/order-service ecommerce/notification-service"