apiVersion: v1
kind: ServiceAccount
metadata:
    name: api-gateway-sa
    namespace: ecommerce
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: inventory-service-sa
    namespace: ecommerce
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: order-service-sa
    namespace: ecommerce
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: product-service-sa
    namespace: ecommerce
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: notification-service-sa
    namespace: ecommerce
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: mailpit-sa
    namespace: ecommerce
automountServiceAccountToken: false
