spring.application.name=order-service
server.port=${SERVER_PORT:8083}

# =========================
# DATABASE
# =========================

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# =========================
# FLYWAY
# =========================

spring.flyway.enabled=true

# =========================
# INVENTORY SERVICE
# =========================

inventory.service.url=${INVENTORY_SERVICE_URL}

# =========================
# KAFKA
# =========================

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
spring.kafka.consumer.group-id=order-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.techie.microservices.order.event

# =========================
# RESILIENCE4J
# =========================

resilience4j.circuitbreaker.instances.inventory.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.inventory.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.inventory.slidingWindowSize=10
resilience4j.circuitbreaker.instances.inventory.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.inventory.failureRateThreshold=50
resilience4j.circuitbreaker.instances.inventory.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.inventory.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.inventory.automaticTransitionFromOpenToHalfOpenEnabled=true

resilience4j.retry.instances.inventory.maxAttempts=3
resilience4j.retry.instances.inventory.waitDuration=2s

# =========================
# ACTUATOR
# =========================

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.endpoint.health.show-components=always
management.health.circuitbreakers.enabled=true

# =========================
# OPENAPI
# =========================

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs

# =========================
# FEIGN
# =========================

spring.cloud.openfeign.client.config.default.connect-timeout=3000
spring.cloud.openfeign.client.config.default.read-timeout=3000
spring.cloud.openfeign.client.config.default.logger-level=basic

# =========================
# FEIGN CIRCUIT BREAKER
# =========================

spring.cloud.openfeign.circuitbreaker.enabled=true

# =========================
# LOGGING
# =========================

logging.level.root=INFO
server.forward-headers-strategy=framework
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{Correlation-Id}] [%thread] %logger{36} - %msg%n

management.metrics.tags.application=${spring.application.name}