spring.application.name=product-service

server.port=${SERVER_PORT:8082}


# =========================
# MONGODB
# =========================

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}


# =========================
# INVENTORY SERVICE
# =========================

inventory.service.url=${INVENTORY_SERVICE_URL}


# =========================
# ACTUATOR
# =========================

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=when_authorized


# =========================
# SWAGGER
# =========================

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs


# =========================
# LOGGING
# =========================

logging.level.root=INFO
logging.level.com.techie.microservices.product=INFO