spring.application.name=inventory-service

server.port=${SERVER_PORT:8081}

# =========================
# DATABASE
# =========================

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


# =========================
# JPA
# =========================

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false


# =========================
# FLYWAY
# =========================

spring.flyway.enabled=true


# =========================
# ACTUATOR
# =========================

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=when_authorized


# =========================
# SWAGGER
# =========================

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true


# =========================
# LOGGING
# =========================

logging.level.root=INFO
logging.level.com.techie.microservices.inventory=INFO