spring.application.name=inventory-service

server.port=${SERVER_PORT:8081}

# =========================
# DATABASE
# =========================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/inventory_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}

spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:user_pass}

# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# =========================
# ACTUATOR
# =========================
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# =========================
# LOGGING
# =========================
logging.level.root=INFO
logging.level.com.techie.microservices.inventory=DEBUG

# =========================
# SWAGGER
# =========================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html